version: '3.8'
services:
  web:
    build: .
    command: gunicorn -c gunicorn.conf.py backend.main:app
    ports:
      - "8080:8080"
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
