version: '3.8'
services:
  web:
    build: .
    image: scanbandz.azurecr.io/scanbandzcoreapis
    command: gunicorn -c gunicorn.conf.py backend.main:app
    ports:
      - "8080:8080"
    volumes:
      - .:/workspace
      
  worker:
    build: .
    image: scanbandz.azurecr.io/scanbandzcoreapis
    command: celery -A backend.settings.celery_worker worker --loglevel=info
    volumes:
      - .:/workspace
