apiVersion: v1
kind: Service
metadata:
  name: github-workflow
  namespace: namespace-workflow-1711352227223
spec:
  type: LoadBalancer
  selector:
    app: github-workflow
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080