# Local development Dockerfile
FROM python:3.11
RUN python3 -m pip install --upgrade pip

# Copy the requirements.txt file into the container
COPY ./requirements.txt /workspace/requirements.txt

# Install dependencies
RUN pip install --no-cache-dir --upgrade -r /workspace/requirements.txt

# Copy app into container
COPY ./backend /workspace/backend

# Set the working directory to /workspace
WORKDIR /workspace

ENV TZ="America/New_York"
EXPOSE 8080

# Uncomment the following line to automatically run the app when the container starts
# Disabled to make reloading with different environment variables easier
# CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]
