version: "3"
# Development
services:
  httpd:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.dev
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ..:/workspace
    depends_on:
      - db
  db:
    image: postgres:15.2
    restart: unless-stopped
    env_file:
      - ../backend/settings/.env
    ports:
      - "5432:5432"
    volumes:
      - sb-postgres-data:/var/lib/postgresql/data
volumes:
  sb-postgres-data:
