"""Add donation receipt entity

Revision ID: aac5b4c5b192
Revises: 0f3eeb335802
Create Date: 2024-03-18 19:01:13.926937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aac5b4c5b192'
down_revision: Union[str, None] = '0f3eeb335802'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donation_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stripe_account_id', sa.String(), nullable=False),
    sa.Column('stripe_transaction_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donation_receipts_id'), 'donation_receipts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_donation_receipts_id'), table_name='donation_receipts')
    op.drop_table('donation_receipts')
    # ### end Alembic commands ###
