"""Alter donation receipt entity

Revision ID: dc900312bf0b
Revises: aac5b4c5b192
Create Date: 2024-03-18 19:09:24.183140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc900312bf0b'
down_revision: Union[str, None] = 'aac5b4c5b192'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donation_receipts', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('donation_receipts', sa.Column('last_name', sa.String(), nullable=False))
    op.drop_column('donation_receipts', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donation_receipts', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('donation_receipts', 'last_name')
    op.drop_column('donation_receipts', 'first_name')
    # ### end Alembic commands ###
