name: (PROD) Publish Docker image to Azure Container Registry

on:
  push:
    branches:
      - main  # Production Workflow

env:
  AZURE_REGISTRY_URL: scanbandz.azurecr.io
  AZURE_REGISTRY_USERNAME: scanbandz
  AZURE_REGISTRY_PASSWORD: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Production

    steps:
    - uses: actions/checkout@v2

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.AZURE_REGISTRY_URL }}
        username: ${{ env.AZURE_REGISTRY_USERNAME }}
        password: ${{ env.AZURE_REGISTRY_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ env.AZURE_REGISTRY_URL }}/scanbandz-core-api:latest