name: Trigger auto deployment for scanbandzcoreapis

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/scanbandzcoreapis-AutoDeployTrigger-ed6f5f7f-b718-4936-9481-e4cc311147fa.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SCANBANDZCOREAPIS_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: scanbandz.azurecr.io
          registryUsername: ${{ secrets.SCANBANDZCOREAPIS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SCANBANDZCOREAPIS_REGISTRY_PASSWORD }}
          containerAppName: scanbandzcoreapis
          resourceGroup: NewScanbandz
          imageToBuild: scanbandz.azurecr.io/scanbandzcoreapis:${{ github.sha }}
          
            

     

